### PR TITLE
AimsVol2Tex_perso

### PR DESCRIPTION
**Pull request by ylep**
This tool is needed by Jessica's team, I would like to make it part of the 5.0 release

### CODE REVIEW

**Review by sapetnioc — APPROVED** [review]
For me it lacks a bit of documentation to know what are exactly doing those parallel parameters. But this is the same on to most Aims commands.

**Comment by ylep** [comment]
> For me it lacks a bit of documentation to know what are exactly doing those parallel parameters. But this is the same on to most Aims commands.

Agreed, to be honest I am not even sure what the use-case is for these parameters... I will try to make it more explicit when I can test it on real data. Anyway thanks for the feedback!

**Comment by denisri** [comment]
This command seems to be a duplicate of `AimsLabels2Tex` in aimsdata... The help is the same, part of the code also, but the code has diverged (of course...). I have modified `AimsLabels2Tex` a couple of months ago, but was not aware of this one...
Well, for now both exist anyway but this is not really good, how should a user know which one suits his needs ?

**Comment by denisri** [comment]
Anyway if Jessica's team needs it, go merge it.

**Review by denisri — APPROVED** [review]
Don't know either what a "parallel texture" is ;)

**Pull request merged**
